export const FETCH_USER = 'users/FETCH_USER'
export const FETCH_USERS = 'users/FETCH_USERS'
export const CREATE_USER = 'users/CREATE_USER'
export const UPDATE_USER = 'users/UPDATE_USER'
export const DELETE_USER = 'users/DELETE_USER'
